# Generated by Django 2.2 on 2019-04-19 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=512)),
                ('address_line2', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=52)),
                ('state', models.CharField(max_length=52)),
                ('country', models.CharField(max_length=52)),
                ('postcode', models.CharField(max_length=22)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(db_column='ID', max_length=512)),
                ('OrderID', models.CharField(db_column='OrderID', max_length=512)),
                ('PackageID', models.CharField(max_length=512)),
                ('ItemDescription', models.CharField(db_column='ItemDescription', max_length=512)),
                ('ItemFullDescription', models.CharField(max_length=512)),
                ('ItemType', models.CharField(max_length=512)),
                ('ItemStatus', models.CharField(max_length=512)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifiedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(db_column='ID', max_length=512)),
                ('CustomerID', models.CharField(db_column='CustomerID', max_length=512)),
                ('OrderSummary', models.CharField(db_column='OrderSummary', max_length=512)),
                ('OrderMessage', models.CharField(db_column='OrderMessage', max_length=512)),
                ('OrderCurrency', models.CharField(db_column='OrderCurrency', max_length=512)),
                ('OrderStatus', models.CharField(db_column='OrderStatus', max_length=512)),
                ('OrderType', models.CharField(db_column='OrderType', max_length=512)),
                ('OrderContact', models.CharField(db_column='OrderContact', max_length=512)),
                ('CreatedDate', models.CharField(db_column='CreatedDate', max_length=512)),
                ('ModifiedDate', models.CharField(db_column='ModifiedDate', max_length=512)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
